### ISSUE TITLE
Efficientnet module missing

### ISSUE THREAD

**Issue by leoxy** [cutz-j/T-GD#2]
When executing eval.py:
Traceback (most recent call last):
  File "eval.py", line 13, in <module>
    from efficientnet import EfficientNet
ModuleNotFoundError: No module named 'efficientnet'

**Comment by leoxy** [comment]
Changing: 
"from efficientnet import EfficientNet"
into:
"from models import EfficientNet"
worked.

**Comment by cutz-j** [comment]
Thanks for the feedback.
I edited this error.
Thanks.
